// This file is auto-generated by @hey-api/openapi-ts

export const $Actor = {
    properties: {
        uid: {
            type: 'string',
            format: 'uuid',
            title: 'Uid'
        },
        namespace_name: {
            type: 'string',
            title: 'Namespace Name'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        creationTimestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Creationtimestamp'
        },
        updateTimestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updatetimestamp'
        },
        labels: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Labels',
            default: {}
        },
        annotations: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Annotations',
            default: {}
        }
    },
    type: 'object',
    required: ['namespace_name', 'name', 'creationTimestamp', 'updateTimestamp'],
    title: 'Actor'
} as const;

export const $ActorsResult = {
    properties: {
        count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Count'
        },
        items: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/Actor'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Items'
        }
    },
    type: 'object',
    title: 'ActorsResult'
} as const;

export const $Event = {
    properties: {
        uid: {
            type: 'string',
            format: 'uuid',
            title: 'Uid'
        },
        namespace_name: {
            type: 'string',
            title: 'Namespace Name'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        actor_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Actor Name'
        },
        item_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Item Name'
        },
        creationTimestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Creationtimestamp'
        },
        updateTimestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updatetimestamp'
        },
        labels: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Labels',
            default: {}
        },
        annotations: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Annotations',
            default: {}
        },
        type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Type'
        },
        value: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Value'
        }
    },
    type: 'object',
    required: ['namespace_name', 'name', 'actor_name', 'item_name', 'creationTimestamp', 'updateTimestamp', 'type', 'value'],
    title: 'Event'
} as const;

export const $EventsResult = {
    properties: {
        count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Count'
        },
        items: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/Event'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Items'
        }
    },
    type: 'object',
    title: 'EventsResult'
} as const;

export const $Feedback = {
    properties: {
        uid: {
            type: 'string',
            format: 'uuid',
            title: 'Uid'
        },
        namespace_name: {
            type: 'string',
            title: 'Namespace Name'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        actor_name: {
            type: 'string',
            title: 'Actor Name'
        },
        item_name: {
            type: 'string',
            title: 'Item Name'
        },
        creationTimestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Creationtimestamp'
        },
        updateTimestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updatetimestamp'
        },
        labels: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Labels',
            default: {}
        },
        annotations: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Annotations',
            default: {}
        },
        type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Type'
        },
        value: {
            type: 'string',
            title: 'Value'
        }
    },
    type: 'object',
    required: ['namespace_name', 'name', 'actor_name', 'item_name', 'creationTimestamp', 'updateTimestamp', 'type', 'value'],
    title: 'Feedback'
} as const;

export const $FeedbacksResult = {
    properties: {
        count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Count'
        },
        items: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/Feedback'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Items'
        }
    },
    type: 'object',
    title: 'FeedbacksResult'
} as const;

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $Item = {
    properties: {
        uid: {
            type: 'string',
            format: 'uuid',
            title: 'Uid'
        },
        namespace_name: {
            type: 'string',
            title: 'Namespace Name'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        creationTimestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Creationtimestamp'
        },
        updateTimestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updatetimestamp'
        },
        labels: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Labels',
            default: {}
        },
        annotations: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Annotations',
            default: {}
        }
    },
    type: 'object',
    required: ['namespace_name', 'name', 'creationTimestamp', 'updateTimestamp'],
    title: 'Item'
} as const;

export const $ItemMinMax = {
    properties: {
        uid: {
            type: 'string',
            format: 'uuid',
            title: 'Uid'
        },
        namespace_name: {
            type: 'string',
            title: 'Namespace Name'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        creationTimestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Creationtimestamp'
        },
        updateTimestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updatetimestamp'
        },
        labels: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Labels'
        },
        annotations: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Annotations'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        min: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min'
        },
        max: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max'
        }
    },
    type: 'object',
    required: ['uid', 'namespace_name', 'name', 'creationTimestamp', 'updateTimestamp', 'labels', 'annotations', 'count', 'min', 'max'],
    title: 'ItemMinMax'
} as const;

export const $ItemWithEventCount = {
    properties: {
        uid: {
            type: 'string',
            format: 'uuid',
            title: 'Uid'
        },
        namespace_name: {
            type: 'string',
            title: 'Namespace Name'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        creationTimestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Creationtimestamp'
        },
        updateTimestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updatetimestamp'
        },
        labels: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Labels'
        },
        annotations: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Annotations'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['uid', 'namespace_name', 'name', 'creationTimestamp', 'updateTimestamp', 'labels', 'annotations', 'count'],
    title: 'ItemWithEventCount'
} as const;

export const $ItemWithEventDetails = {
    properties: {
        uid: {
            type: 'string',
            format: 'uuid',
            title: 'Uid'
        },
        namespace_name: {
            type: 'string',
            title: 'Namespace Name'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        creationTimestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Creationtimestamp'
        },
        updateTimestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updatetimestamp'
        },
        labels: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Labels'
        },
        annotations: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Annotations'
        },
        eventUid: {
            type: 'string',
            format: 'uuid',
            title: 'Eventuid'
        },
        eventName: {
            type: 'string',
            title: 'Eventname'
        },
        eventActor: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Eventactor'
        },
        eventCreated: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Eventcreated'
        },
        eventUpdated: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Eventupdated'
        },
        eventLabels: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Eventlabels'
        },
        eventAnnotations: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Eventannotations'
        },
        eventType: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Eventtype'
        },
        eventValue: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Eventvalue'
        }
    },
    type: 'object',
    required: ['uid', 'namespace_name', 'name', 'creationTimestamp', 'updateTimestamp', 'labels', 'annotations', 'eventUid', 'eventName', 'eventActor', 'eventCreated', 'eventUpdated', 'eventLabels', 'eventAnnotations', 'eventType', 'eventValue'],
    title: 'ItemWithEventDetails'
} as const;

export const $ItemWithFeedbackCount = {
    properties: {
        uid: {
            type: 'string',
            format: 'uuid',
            title: 'Uid'
        },
        namespace_name: {
            type: 'string',
            title: 'Namespace Name'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        creationTimestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Creationtimestamp'
        },
        updateTimestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updatetimestamp'
        },
        labels: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Labels'
        },
        annotations: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Annotations'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['uid', 'namespace_name', 'name', 'creationTimestamp', 'updateTimestamp', 'labels', 'annotations', 'count'],
    title: 'ItemWithFeedbackCount'
} as const;

export const $ItemsResult = {
    properties: {
        count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Count'
        },
        items: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/Item'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Items'
        }
    },
    type: 'object',
    title: 'ItemsResult'
} as const;

export const $MinMax = {
    properties: {
        count: {
            type: 'integer',
            title: 'Count'
        },
        min: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min'
        },
        max: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max'
        }
    },
    type: 'object',
    required: ['count', 'min', 'max'],
    title: 'MinMax'
} as const;

export const $Namespace = {
    properties: {
        uid: {
            type: 'string',
            format: 'uuid',
            title: 'Uid'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        creationTimestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Creationtimestamp'
        },
        updateTimestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updatetimestamp'
        },
        labels: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Labels',
            default: {}
        },
        annotations: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Annotations',
            default: {}
        }
    },
    type: 'object',
    required: ['name', 'creationTimestamp', 'updateTimestamp'],
    title: 'Namespace'
} as const;

export const $NamespacesResult = {
    properties: {
        count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Count'
        },
        items: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/Namespace'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Items'
        }
    },
    type: 'object',
    title: 'NamespacesResult'
} as const;

export const $Stats = {
    properties: {
        namespaces: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Namespaces'
        },
        actors: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Actors'
        },
        items: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Items'
        },
        events: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Events'
        },
        feedbacks: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Feedbacks'
        }
    },
    type: 'object',
    title: 'Stats'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;