FROM registry.access.redhat.com/ubi9/python-311

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
CMD ["python", "-m", "fastapi_cli", "run"]
